version: '3.8'

services:
  company-app:
    build: .
    container_name: company-app-container
    ports:
      - "8090:8090"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/USERAPI?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-container
    restart: always
    environment:
      - MYSQL_DATABASE=USERAPI
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: